### ISSUE TITLE
[Bug] Incompatibility with Custom Moons

### ISSUE THREAD

**Issue by Agitatio** [flerouwu/LC_FastStartup#2]
Using custom moons with LC_FastStartup results in you getting sent back to the main menu as soon as you route to a custom moon and pull the lever.

**Comment by flerouwu** [comment]
Thanks for reporting this! I can confirm there's some kind of issue with the mod, and I'm looking into it.

**Comment by flerouwu** [comment]
~~Hey @Agitatio! Can you please send me your mod list? If you are using r2modman or Thunderstore, you can go to your profile and select `Settings > Profile > Export profile as a code` and paste the code in a comment.~~

EDIT: Not needed, I had thought that it was an issue with certain mods.

**Comment by Agitatio** [comment]
I checked this without any other mods. You can just download E Gypt (and its dependencies) and FastStartup. Start the game, route to EGypt, pull the lever and you'll be sent to the menu.

**Comment by flerouwu** [comment]
This has been fixed in [this commit](https://github.com/flerouwu/LC_FastStartup/commit/16b75249868c1977edbe92aff1786e9f4681f4ac).
I'm currently building the project to be uploaded to Thunderstore. This update should be out in the next 10 minutes.

Thanks for reporting this issue! If you still experience issues, please comment back on this issue and I'll look into it again.

**Comment by flerouwu** [comment]
The new mod version has been published to Thunderstore. You can see the version page [here](https://thunderstore.io/c/lethal-company/p/flerouwu/LC_FastStartup/versions/).

It may take a few moments for r2modman / Thunderstore to register that there is an update.
